# Generated by Django 4.2.7 on 2023-11-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pro_pic',
            field=models.ImageField(upload_to='image'),
        ),
    ]
